---

- name: Install nfs-utils
  yum:
    name: nfs-utils
    state: latest

- name: mount the nfsshare in client side
  mount:
    fstype: nfs
    opts: hard,bg
    dump: 0
    passno: 0
    state: mounted
    src: "{{ item.src }}"
    path: "{{ item.path }}"
  with_items: "{{ nfsmounts }}"
