---

- hosts: localhost
  roles:
    - ssh-key
  vars:
    ssh_key_name: ansible_remote
    hashicorp_vault_private_key_path: "/applications/heritage-{{ environment_name }}-eu-west-2/tuxedo/aws"

- hosts: aws_ec2
  serial: 1
  remote_user: centos
  become: yes
  roles:
    - deploy
