---

roles:
  - src: https://github.com/companieshouse/ansible-role-ssh-key
    name: ssh-key
    version: "1.0.0"

collections:
- name: amazon.aws
- name: community.general
- name: community.hashi_vault
