plugin: aws_ec2
boto_profile: heritage-development-eu-west-2

regions:
  - eu-west-2

filters:
  tag:Environment: development
  tag:Service: tuxedo
  tag:ServiceSubType: frontend

hostnames: private-ip-address
